### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [bitllenetwork/bitllejs#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/bitllenetwork/bitllejs/blob/master/package.json#L23

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by AlexeySalyk** [comment]
A new version of the package was published
